### ISSUE TITLE
Autoprefixer integration

### ISSUE THREAD

**Issue by foxacid** [cferdinandi/build-tool-boilerplate#19]
Sorry, it's me again with a feature request 😊

Are there any plans/possibilities for adding CSS autoprefixing? I'm not sure how PostCSS would play along in this configuration and whether integration is feasible. Any ideas?

**Comment by cferdinandi** [comment]
Hi there! autoprefixer actually uses and requires PostCSS.

That said, I generally recommend against autoprefixing these days, since modern support for unprefixed CSS properties is so good.

**Comment by foxacid** [comment]
Fair enough and I generally agree. I'm currently working on a project that uses CSS Grid Layout and  need to supply basic support for IE11. Autoprefixer would make my life a lot easier, hence the question 😉
