### ISSUE TITLE
Add autoprefixer

### ISSUE THREAD

**Issue by Pixelizer** [cferdinandi/build-tool-boilerplate#24]
Hi, is it possible to add autoprefixer to the boilerplate. And if yes, can you show me how i can do this? Thanks, P.

**Comment by cferdinandi** [comment]
- It is
- I don't use it (I don't think it's necessary in a modern autoupdating browser landscape), so I can't tell you specifically how to add it
- You can find [docs on using it with the command line here](https://github.com/postcss/autoprefixer#cli) - hopefully that can help get you started
