### ISSUE TITLE
Problems in *css.min - Sass

### ISSUE THREAD

**Issue by Pixelizer** [cferdinandi/build-tool-boilerplate#25]
Hello,

my *css.min file is wired. My Dev tool show me every styling should be in my last loaded script. But is is wrong. Is there a problem with the .min compile or is there something wrong in one of my loaded scss inside app.scss files?

**Comment by cferdinandi** [comment]
Please provide a reduced test case.

**Comment by Pixelizer** [comment]
Hi,

this is a part in my app.scss.

`/* settings */
@import '0-settings/normalize';
@import '0-settings/settings';
@import '0-settings/mixin';

/* global */
@import '1-global/basics';
@import '1-global/gaps';
@import '1-global/colors';
@import '1-global/accessibility';
@import '1-global/typography';

/* elements */
@import '2-elements/body';
@import '2-elements/content';
@import '2-elements/icons';
@import '2-elements/grid';
@import '2-elements/site-header';
@import '2-elements/site-navigation';
@import '2-elements/site-footer';
@import '2-elements/site-pagebar';
@import '2-elements/scroll-top';
@import '2-elements/captions';
@import '2-elements/alignments';`

I select "pxlr-site-header-wrapper" and the styling is placed in "site-header" scss. But the inspector/Devtools say it is places in alignment.scss row 39. When i delete the @import for 2-elements/alignment and rebuild my css. Devtools say the style for  "pxlr-site-header-wrapper" is placed in "captions" scss file in line xxx. How ever, devtool says always it will be placed in the last imported file :-/

![Bildschirmfoto 2021-11-08 um 16 03 01](https://user-images.githubusercontent.com/6263680/140765831-9dca037a-3306-4b0a-9ac0-3041f5083949.png)

**Comment by cferdinandi** [comment]
Sorry, but can you please provide a link to actual code I can test? Preferably, remove everything but the affected code. Thanks!

**Comment by Pixelizer** [comment]
Hm. it is every thing in development locally, maybe we can do a google video chat and I share my screen, is this an option?

**Comment by cferdinandi** [comment]
I'm going to close this issue for now. If you can provide a reduced test case in the future, happy to take a look.

**Comment by cferdinandi** [comment]
For more information on what that is: https://css-tricks.com/reduced-test-cases/

**Comment by Pixelizer** [comment]
Ah perfect, thanks for that link. I will check this out and build a reduced test case.
