### ISSUE TITLE
Watch task?

### ISSUE THREAD

**Issue by zenbug** [cferdinandi/build-tool-boilerplate#3]
I've love a watch task using BrowserSync or whatever. Any plans for that?

**Comment by cferdinandi** [comment]
I've been too lazy to bolt one in, but I think that would be awesome! I'm open to PRs on that.

**Comment by cferdinandi** [comment]
Now implemented in v2 thanks to an amazing PR from @simonminter (and a few small changes from me): https://github.com/cferdinandi/build-tool-boilerplate/pull/4
